# Stage 1: Build (Installation des dépendances)
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
# On installe uniquement les dépendances de production pour alléger l'image
RUN npm ci --omit=dev 

# Stage 2: Production
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# On copie uniquement ce qui est nécessaire
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
# On copie les fichiers de l'application (index.js, db.js, dossiers routes/models/etc.)
COPY . .

EXPOSE 3000
USER node 
# L'application démarre via index.js
CMD ["node", "index.js"]